const MODULE_NAME = 'dataLog'

export const STORE_DATA_LOG_MODULE = {
  MODULE_NAME: MODULE_NAME,
  DATA_LOGS: MODULE_NAME + '/DATA_LOGS',
  FIND_ALL: MODULE_NAME + '/FIND_ALL',
  GET_BY_DATE: MODULE_NAME + '/GET_BY_DATE',
  SAVE_ALL: MODULE_NAME + '/SAVE_ALL',
}
